---
- module: "item_analyzer",
  output_directory: "../../contents/movielens_test_exo_prop"
  source:
    - class: 'json'
      file_path": 'movies_info_reduced'
  id:
  - 'imdbID'
  get_exogenous_properties:
    - class: 'dbpedia_mapping'
      mode: 'only_retrieved_evaluated'
      entity_type: 'Film'
      lang: 'EN'
      label_field: 'Title'
  fields: []

- module: "ratings"
  source:
    - class: 'dat'
      file_path": 'file-path'
  from_field_name: "user_id"
  to_field_name: "item_id"
  timestamp_field_name: "timestamp"
  output_directory: "file_path"
  rating_configs:
    - class: "ratings_config"
      field_name: "recensione"
      processor:
        class: "text_blob_sentiment"
    - class: "ratings_config"
      field_name: "stelle"
      processor:
        - class: "number_normalizer"
          min: "1"
          max: "5"